
# Configuration file for SimCLR training

epochs: 500
eval_every: 10
warmup_epochs: 10

data:
  dataset_name: cifar10
  batch_size: 256
  transforms:
    train:
      color_jitter:
        brightness: 0.4
        contrast: 0.4
        saturation: 0.4
        hue: 0.1
        p: 0.8
      random_gray:
        p: 0.2
      gaussian_blur:
        sigma: [0.1, 2.0]
        p: 0.5
      random_resized_crop:
        size: [32, 32]
        scale: [0.2, 1.0]
        p: 0.5
      random_horizontal_flip:
        p: 0.5
      normalize:
        mean: [0.4914, 0.4822, 0.4465]
        std: [0.2470, 0.2435, 0.2616]
    test:
      center_crop:
        size: 32
      normalize:
        mean: [0.4914, 0.4822, 0.4465]
        std: [0.2470, 0.2435, 0.2616]

encoder:
  reduce_bottom: True

projection_head:
  proj_dim: 1024
  
optimizer:
  name: sgd
  lr: 1.0
  momentum: 0.9
  nesterov: True
  weight_decay: 1.0e-06
  
scheduler:
  name: cosine
  lr: 1.0
  decay_steps: 500
  alpha: 0.0

loss_fn:
  normalize: False
  temperature: 0.5

linear_eval:
  epochs: 100
  batch_size: 256
  learning_rate: 0.1

wandb:
  project: self-supervised-vision